### ISSUE TITLE
[1.12 Forge] NullPointerExceptions

### ISSUE THREAD

**Issue by Blatts12** [makamys/MAtmos#1]
latest.log: https://pastebin.com/D16vrQnY
I have the Zen Soundpack

**Comment by makamys** [comment]
Thanks for reporting, it turned out to be a simple mistake.
Can you verify that this change fixes it? Here's a build of the new jar:
[matmos-1.12.2-34.2.1-SNAPSHOT.zip](https://github.com/makamys/MAtmos/files/4490690/matmos-1.12.2-34.2.1-SNAPSHOT.zip)

**Comment by Blatts12** [comment]
I flew around and nothing happened so i think it's fixed

**Comment by makamys** [comment]
Closing this as it's fixed in MAtmos 35.
