### ISSUE TITLE
MAtmos Maxblock ID trigger and crash when wielding GT6 items with high metadata values (even with 8K+ block IDs enabled)

### ISSUE THREAD

**Issue by SilearFlare** [makamys/MAtmos#11]
I've been experiencing these often lately, my console gets spammed infinitely until I turn off MAtmos entirely, and it happens again if I turn it off and turn it on again.

Here's the pastebin link of an excerpt of the crash (because nobody needs to read the same paragraph over and over) https://pastebin.com/ZF3YwjwA

Just from a cursory glance none of the mods are involved, but I can upload an instance if needed, any help with this is very much appreciated.

**Comment by SilearFlare** [comment]
oh wait dang I should have been checking the issues better, it looks like other people have had this crash too. I just need to edit the maxblockID :thinking:

**Comment by SilearFlare** [comment]
Nevermind, it's a bit of a weird bug.

**Comment by SilearFlare** [comment]
I can finally confirm the source of these bugs: when wielding certain items matmos will crash, spamming the console. As of now, the crash itself seems to happen randomly when wielding GT items or tools with metadata in the order of tens of thousands (milk bottle, drain, crowbar etc), even with a block ID limit of 32K+.

**Comment by SilearFlare** [comment]
Danke, matmosman

**Comment by makamys** [comment]
Some clarification for posterity's sake: we worked out the solution elsewhere, the issue happened with Techguns+GT6 items and setting `dealias.oredict=false` in the config fixed it as a workaround.
