### ISSUE TITLE
Question about sound packs and multiblock structures...

### ISSUE THREAD

**Issue by juraj-hrivnak** [makamys/MAtmos#13]
### Do you think that will be possible to make a sound pack that checks for active Immersive Engineering multiblock structure?

- Like if you want to add sound for an active machine. Because a lot of Immersive Engineering multi blocks don't have sounds and I was thinking of the easiest way to adding them. 

Thanks.

**Comment by makamys** [comment]
Hey, is there any particular reason you closed this? I don't think MAtmos is capable of this right now, but I think it's a cool idea, might look into it later.
