### ISSUE TITLE
TFC+ update builtin alias

### ISSUE THREAD

**Issue by facetorched** [makamys/MAtmos#19]
There is now `terrafirmacraftplus:leaves3`. Also, i'm not sure `terrafirmacraftplus:Branch` is a valid block (there are like 50 blocks that are used for trees). Maybe if you allow for a wildcard like `terrafirmacraftplus:Branch*` it would work.

Lastly, there was a sling weapon that was added. not sure if there's an alias for something like that.

**Comment by makamys** [comment]
Wildcards are indeed supported, you can see this in use in the Thermal Foundation entries:
https://github.com/makamys/MAtmos/blob/d66ab26727b6d5ca324c06194afe7dd3d91d9a73/projects/1.7/src/main/resources/assets/matmos/default_config/builtin_aliases/misc.map#L16-L18

I can't work on this issue right now, but if you post an updated alias map (either as a PR or a paste) I'll add it.

**Comment by makamys** [comment]
Closing as fixed in https://github.com/makamys/MAtmos/pull/20.
