### ISSUE TITLE
Sounds keep cutting out with DynamicSounds installed

### ISSUE THREAD

**Issue by TheDominooos** [makamys/MAtmos#21]
game version: 1.12.2
forge version: 14.23.5.2860

Mods:
OreLib-1.12.2-3.6.0.1
matmos-1.12.2-35.4.3.jar
DynamicSurroundings-1.12.2-3.6.3

When many mobs are in one place (it starts happening with around 20 mobs), mob sounds cut out right after they start playing. This happens with or without any matmos sound packs loaded. The issue appears with less mobs (5-10 mobs) during rain. The issue persists with matmos disabled in the F4 menu.

What I tried:
- refreshing sounds with F3-T
- using older versions of matmos and dynamic surroundings
- increasing number of normal and streaming sound channels,  in dynamic surroundings config file
- using https://www.curseforge.com/minecraft/mc-mods/extendpolyphonylimit

**Comment by makamys** [comment]
https://github.com/makamys/MAtmos/blob/4272f3b62a2d31a9d6ffa22a2399587d58dfe9fe/projects/1.12/src/main/java/eu/ha3/matmos/core/mixin/MixinSoundManager.java#L33-L34

MAtmos is hardcoded to use 11 streaming channels and 21 normal channels, I'll have to change this to be configurable and respect other mods' settings.

**Comment by makamys** [comment]
https://github.com/makamys/MAtmos/suites/7956053091/artifacts/339879057
Try this new build. Now the settings set by Dynamic Surroundings or ExtendPolyphonyLimit are kept, plus the default channel count used when no other mod changes it has been doubled.

**Comment by TheDominooos** [comment]
> 

The new build fixed the issue for me, thanks.
