### ISSUE TITLE
ReadOnlyFileSystemException crash?

### ISSUE THREAD

**Issue by xJon** [makamys/MAtmos#23]
Got a report from a user who wasn't able to enter their world when MAtmos was installed due to this issue: https://mclo.gs/Ctp9Sd0.
Not sure whether something was wrong with their setup, but upon removing MAtmos they apparently were able to play.
I somehow doubt this is an issue with the mod, and I do ship the mod's config files with the modpack, but I thought to report it nonetheless in case you better understand what's going on.

**Comment by makamys** [comment]
Oh, this is the same problem as https://github.com/makamys/Mixingasm/pull/1 (which uses the same code for generating configs as MAtmos), I just haven't merged in the fix. I'll do that in a moment.

**Comment by xJon** [comment]
Awesome, thanks :)
