### ISSUE TITLE
NoSuchElementException: No value present

### ISSUE THREAD

**Issue by Apemon7** [makamys/MAtmos#3]
latest.log: https://pastebin.com/GSHKkJV0
crash-report: https://pastebin.com/K9wHp6EW

When loading a world in single-player or multi-player, the game crashes to desktop.
Seems to occur when start.enabled=false in the config before launching the game.
Also could be due to other mods running. Mods listed in the crash-report.

**Comment by makamys** [comment]
Oh, it crashes for me as well, I never tested with that option. The mod works if it's set to true though, right?

**Comment by Apemon7** [comment]
Yeah, went into the config and set it back to true and it worked fine. It may also be related to the fact that I had the resource pack on while the mod was off. Haven't tested it though and I don't know if it is related.

**Comment by makamys** [comment]
Closing this as it's fixed in MAtmos 35.
