### ISSUE TITLE
Latest version (1.7.10-36.0.1) doesn't seem to have a downloadable copy, either on curseforge or in the github.

### ISSUE THREAD

**Issue by PlayfulPiano** [makamys/MAtmos#35]
Saw the popup ingame about a new update, but there doesn't seem to be a version ready to be downloaded.

**Comment by MagmaSlime123** [comment]
Same issue.

**Comment by makamys** [comment]
It did get submitted to CurseForge, it's just still under approval. It's just the GitHub release that's missing jars for some reason, oops. I added them now.
