### ISSUE TITLE
Seems HEE hates 36.0.1.

### ISSUE THREAD

**Issue by MagmaSlime123** [makamys/MAtmos#37]
Title.

[crash-2024-02-15_21.05.36-client.txt](https://github.com/makamys/MAtmos/files/14305638/crash-2024-02-15_21.05.36-client.txt)
[fml-client-latest.log](https://github.com/makamys/MAtmos/files/14305641/fml-client-latest.log)

**Comment by makamys** [comment]
> `Examining for coremod candidacy matmos-1.12.2-36.0.1+nomixin.jar`

You're using the 1.12.2 version of MAtmos on 1.7.10, no wonder it doesn't work.

**Comment by MagmaSlime123** [comment]
Ah, didn't see you put both 1.12.2 and 1.7.10 jars together. My bad lol.
