### ISSUE TITLE
Matmos crash with Eternal Modpack

### ISSUE THREAD

**Issue by ghost** [makamys/MAtmos#9]
Hello
Matmos crashes and spam console full of things.
I added Matmos with Optifine to MC Eternal Modpack.
Did a Clean install, use the last version from Java and also did a run without other sounds mods from MC Eternal.
Here a the logs from a new flat world in Singleplayer . I quickly disconnect that the log not getting so big.

[LOGoutput](https://paste.gg/p/anonymous/68b915fc5cbc49108e709d9097f415da)

Thanks in advance!

**Comment by makamys** [comment]
This is a known issue with NotEnoughIDs/JustEnoughIDs (#2). The current workaround is to raise `world.maxblockid` in the config. I plan on lifting this limitation eventually.

**Comment by ghost** [comment]
Alright , basic things like config file editing should be not a problem.
What file i need to edit?

**Comment by makamys** [comment]
`.minecraft/config/matmos/userconfig.cfg`

**Comment by ghost** [comment]
I took the block number from the Mod page and i can join now without Matmas crash but there are a new spam 
messages now : [Thread-15/ERROR] [minecraft/SoundManager]: Error in class 'LibraryLWJGLOpenAL'
 [Thread-15/ERROR] [minecraft/SoundManager]: Sourcename not specified in method 'stop'

The game also make some "Ding" sounds.
I can't describe it very well so i did a short video with that sound. ( Happens mostly at night with or without mobs)

But i'm not quite sure if this caused by Matmos?

Log uploaded by MultiMC 
so it looks a little bit different now :https://paste.ee/p/oN60U

Video where that "Ding" sound happens :

https://user-images.githubusercontent.com/12958303/104163775-3d92f200-53f7-11eb-9912-61e617e51290.mp4

**Comment by makamys** [comment]
Huh, I have no idea. Does it happen without MAtmos?

**Comment by ghost** [comment]
In Vanilla Minecraft it is the GUI sound effect when i pick up 
new blocks or made some new achievements in the upper right corner.
Because i use a Skyrim Resource Pack the sound was different.

I try out the next day without matmos and see what happens

**Comment by ghost** [comment]
It happens without Matmos and my Resource Pack also. But with Matmos it comes quicker. 

The point from my post was the crash and not the other one that now happens. ( i have digressed from the topic)
You can close this thread.
Many thanks for helping out!
